version: '3.7'

services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: SUPERsecret
    volumes:
      - '/Users/vasilijkazmin/Downloads/postgresql_data:/var/lib/postgresql/data'
    networks:
      - keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: SUPERsecret
      KC_HOSTNAME: localhost
    ports:
      - "8443:8443"
      - "9000:9000"
    networks:
      - keycloak
    depends_on:
      - postgresql

networks:
  keycloak:
    driver: bridge
