version: '3'
services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=SUPERsecret
    volumes:
      - '/Users/vasilijkazmin/Downloads/postgresql_data_2:/var/lib/postgresql/data'
    networks:
      - key_cloak_keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    restart: always
    command: start-dev
    depends_on:
      - postgresql

    volumes:
      - ./certs:/opt/keycloak/certs
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME=localhost
      - KC_HTTPS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=SUPERsecret
      - KC_DB_SCHEMA=public
      - KC_DB_URL=jdbc:postgresql://postgresql:5432/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/localhost_cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/localhost_key.pem
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - key_cloak_keycloak

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/vasilijkazmin/Downloads/portainer_data:/data
      - ./certs:/certs  # Подключаем папку с сертификатами
    environment:
      - KEYCLOAK_BASE_URL=https://localhost:8443
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=portainer-3
      - KEYCLOAK_CLIENT_SECRET=yXODJfD7UfvFvgJsHvCUrJ8GkRan0kVy
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    networks:
      - key_cloak_keycloak
    command: >
      -H unix:///var/run/docker.sock
      --ssl
      --sslcert /certs/localhost_cert.pem
      --sslkey /certs/localhost_key.pem

networks:
  key_cloak_keycloak:
    external: true